server:
  port: 9095
  ssl:
    enabled: true
    key-alias: test
    key-store-password: 123456
    key-store: classpath:test.pfx
    key-store-type: PKCS12

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello-rotue
          uri: lb://hello-service
          predicates:
            - Path=/hello-service/**
          filters:
            - StripPrefix=1

        - id: testBaidu
          uri: http://www.baidu.com
          predicates:
            - Query=name,ly
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: false


#      routes:
#        - id: myRoute
#          uri: lb://service
#          predicates:
#            - Path=/service/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
    register-with-eureka: true
#zuul:
#  routes:
#    api-hello:
#      path: /api-hello/**
#      serviceId: hello-service
#    api-hi:
#      path: /api-hi/**
#      serviceId: hi-service
debug: true
