debug: true

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: 1234
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
              filters: stat
              maxActive: 20
              initialSize: 1
              maxWait: 60000
              minIdle: 1
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 300000
              validationQuery: select 'x'
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true
              maxPoolPreparedStatementPerConnectionSize: 20
              maxOpenPreparedStatements: 20

mybatis:
    mapper-locations: classpath:mapper/**.xml
    type-aliases-package: com.ly.entity  # 注意：对应实体类的路径


logging:
   level:
     com:
       ly:
         dao:
           test: debug
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



